### ISSUE TITLE
Download Tracking & Analytics

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator#30]
## Progress

- [x] Tracking
- [x] Reporting
- [x] API

## Tracking

Download tracking works by exposing a tracking URL that goes through Phoenix before redirecting to the actual requested file. Phoenix asynchronously persists the download.

Attributes of the tracking system:

- downloads must still work even if tracking system is slow or down
- bot requests (or in general: not real downloads) are detected and discarded
- duplicate requests are detected and merged

In general, [IAB Guidelines](https://www.iab.com/guidelines/podcast-measurement-guidelines/) should be followed.

## Analytics

Analytics provide aggregated views on the raw download data. For good viewing performance independent from amount of downloads, data needs to be pre-calculated. Side benefit of pre-calculating all reports is that old raw tracking data can be discarded.

### Podcast Reports

- total downloads
- downloads per month
- downloads per day
- User Agent analytics per month (client, operating system, device type)
- Geo Analytics (countries, cities via maxmind GeoLite2)

### Episode Reports

- total downloads
- downloads per month
- downloads per day
- downloads [1d/2d/3d/4d/5d/6d/1w/2w/4w/1q/2q/3q/1y] after release, providing numbers _relative to publication date/time_ (time frames taken from Podlove Publisher; however, how useful are time frames > 1q, really?)

### API

All reporting data must be accessible via API.

## Boring Tech Stack

We considered using [elastic stack](https://www.elastic.co/) for tracking & analytics. However, the longer I look at it the more daunting the infrastructure complexity becomes. Yes, it’s a great stack for wading through log data _but_ it’s also a whole stack that needs to be learned, setup and maintained. And since I _know_ that the boring approach, logging download requests into Postgres, works, I have a hard time making elastic a core dependency at this point.

**Comment by eteubert** [comment]
Is next up but requires #33 (file abstractions) to be done.

**Comment by eteubert** [comment]
Tracking Checklist

- [ ] fetch episode, podcast and network
- [ ] detect and ignore HEAD requests
- [ ] parse user agents
- [ ] ignore bots
